name: postgres
version: '0.1'
title: PostgreSQL database
summary: PostgreSQL Database for ctrlX
description: |
  PostgreSQL also known as Postgres, is a free and open-source relational database management system (RDBMS) emphasizing extensibility and SQL compliance. PostgreSQL features transactions with atomicity, consistency, isolation, durability (ACID) properties, automatically updatable views, materialized views, triggers, foreign keys, and stored procedures. It is designed to handle a range of workloads, from single machines to data warehouses or web services with many concurrent users. 

base: core22
grade: stable
confinement: strict
type: app
architectures:
  - arm64

system-usernames:
  snap_daemon: shared

#plugs:
#  shared-memory: 
#    private: true

#layout:
#  binds:
#    /tmp/.s.PGSQL.5432:
#      /var/snap/postgres/current/solutions/activeConfiguration/tmp

apps:
  postgres:
    command: launcher.sh
    daemon: forking
    restart-condition: always
    plugs:
      - network
      - network-bind
      - socket
    passthrough:
      restart-delay: 20s

#  drop-user:
#    command: drop-user
#    daemon: simple
#    plugs:
#      - home
#      - network

parts:
  postgres:
    source: git@github.com:postgres/postgres.git
    plugin: autotools
    stage-packages:
      - libreadline-dev
      - libicu-dev
      - libpq-dev
      - util-linux

#  drop-user:
#    source: drop_user
#    plugin: make

  scripts:
    source: snap/local
    plugin: dump

  configs:
    plugin: dump
    source: configs
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

#  data:
#    plugin: dump
#    source: data

#plugs:
#  active-solution:
#    interface: content
#    content: solutions
#    target: $SNAP_DATA/solutions

#slots:
#  package-run:
#    interface: content
#    content: package-run
#    source:
#      write:
#      - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}
      
hooks:
  connect-plug-active-solution:
    plugs: [active-solution]

